### ISSUE TITLE
Automatic Reconnect

### ISSUE THREAD

**Issue by devinfoley** [murphjm/JavaPusherClient#2]
Using this library on Android over a mobile data connection is problematic because the connection can drop out and be terminated, and fails to reconnect automatically.

Any ideas how to fix this? Is there any way to make the client reconnect automatically?

If this functionality needs to be implemented, can you point me in the right direction so I can fork and add it?

Thanks for the great work!

**Comment by murphjm** [comment]
Hey Devin,

I initially wrote a reconnect thread loop into the client, but decided it would be best to let the individual clients handle it. 

You probably want to spin up a background thread that periodically checks the state of the socket / connection and reconnects as necessary. 

Does that make sense? 

Please let me know if you have any other questions. 

T,

</Justin>
